### ISSUE TITLE
Look into publishing on Chrome Web Store

### ISSUE THREAD

**Issue by kkkrist** [kkkrist/chromium-notifier#14]
https://developer.chrome.com/webstore/publish

**Comment by AGlezB** [comment]
Chromium 80.0.3960.0 (Official Build) (64-bit) seems to require extensions to come from the store.
![image](https://user-images.githubusercontent.com/12277525/68475785-d59bb700-0207-11ea-9ffa-334160b95a60.png)

The _Learn more_ page says: `To protect you while you browse, Chrome only lets you use extensions that have been published on the Chrome Web Store.`

I followed the install instructions in `README.md`. Did I miss something?

**Comment by kkkrist** [comment]
Oh wow… thanks for bringing this up. Are you able to manually enable the extension with the switch (might require developer mode) or is it not possible at all?

I'm still on Chromium v78 (current stable), where I can freely install (and enable) the extension with and without developer mode enabled. I guess this is a change introduced in later versions, a rather controversial one to put it mildly. One of the reasons I use Chromium and not Chrome is to escape Google lock-in after all.

I'll investigate and see what I can do.

**Comment by AGlezB** [comment]
> Are you able to manually enable the extension with the switch (might require developer mode) or is it not possible at all?

Not possible at all. I though I was doing something wrong so I flipped the switch several times.

> One of the reasons I use Chromium and not Chrome is to escape Google lock-in after all.

Same here.

> I'll investigate and see what I can do.

Thanks a lot!

**Comment by kkkrist** [comment]
@AGlezB I've updated the [README](https://github.com/kkkrist/chromium-notifier#readme) with an alternate installation method which should work for you, see [Installing via "Load unpacked extension"](https://github.com/kkkrist/chromium-notifier#installing-via-load-unpacked-extension).

Additionally I'll list the extension in the Chrome Web Store as soon as the PR for #16 lands. The fact that I use a proxy to circumvent CORS won't help to get through the review process, so that has to come first.

As to the root cause of the warning and whether it's something that's been introduced in Chromium 79 or 80, I can't tell. I've skimmed briefly through the source code and found the string itself (`IDS_EXTENSIONS_ADDED_WITHOUT_KNOWLEDGE`) included years ago. So the whole behaviour probably isn't new and triggered by some heuristics. 

If anybody knows more, I'd love to hear!

**Comment by AGlezB** [comment]
@kkkrist It does work. Thanks.

**Comment by kkkrist** [comment]
Closing. I don't think I'll publish this extension on the Chrome Web Store in the near future. It'll probably draw more attention than I can handle right now. The proxy is already running on the limit of what of the current (free plans) hosting setup allows and I want to concentrate on other projects for now. 

Anyway, the extension works fine as it is and I guess people really interested are fine with the manual/dev-mode install.
