### ISSUE TITLE
Excessive CPU/GPU consumption

### ISSUE THREAD

**Issue by leo-liar** [kkkrist/chromium-notifier#25]
Hello there,

firstly, thank you very much for this extension.

Recently (since the last 2 version if I recall correctly) the extension is using excessive amounts of GPU and CPU processing power. Enough that my laptop fan is running at full speed while I'm actually doing nothing. While idling Process Explorer tells me that it uses constantly up to 20% of my CPU and almost 50% of my GPU.

I'm on Windows 10 x64 Version 1809. My laptop uses an Intel Core i7-8550U, has 16GB of RAM and an Intel UHD Graphics 620.

Would be nice if you could take a look into that.

**Comment by kkkrist** [comment]
Hey leo-liar,

thanks for reporting this problem! Could you please do the following:

* Go to `chrome://extensions/` and click on the "background page" ("background.html")  link of the extension's tile. A Devtools window connected to the extension will open. Please check if there are any messages on the Console-Tab and post them here

* Please check if the problem already exists in older versions (specifically pre-1.7.0) and tell me the last version that works correctly.

**Comment by kkkrist** [comment]
Ok, I think I've found the culprit. The new error tracking handler could cause an infinite loop if the error event does not look as expected. This is a really stupid mistake, I'm sorry! I'll release v1.7.2 in a minute, it should fix it. Please try the new version and report back! Thanks!

**Comment by leo-liar** [comment]
Ah, wow, thanks for the quick reply and (possible) fix. I just updated the extension and will keep an eye on it throughout the day.
So far everything seems to be okay. I will report back if the error reappears.

---

EDIT:
Your fix seems to definitively have resolved the excessive CPU consumption issue.
