### ISSUE TITLE
crx required proof missing

### ISSUE THREAD

**Issue by lrq3000** [kkkrist/chromium-notifier#28]
I am getting this error when trying to install the plugin, even under developer mode. I have just installed chromium, so it's the latest version (79.0.3945.88). Any idea what I could try?

**Comment by lrq3000** [comment]
Ah so it doesn't work with the .crx, but with the unpacked folder it works fine :-)

**Comment by kkkrist** [comment]
Thanks for reporting this problem! It looks like Google is locking out "unofficial" extensions (i.e. not obtained from Chrome Web Store / compiled with an unsigned key) from installing without dev mode more and more, see also #14.

I'll try to list the extension in the store soon™, even though it leaves a bad taste in my mouth for various reasons.

**Comment by lrq3000** [comment]
Thank you for looking into this! I understand, but meanwhile it would maybe be useful to update the readme to clarify that for the moment the crx plugin does not work?

**Comment by kkkrist** [comment]
It's not that it doesn't work at all anymore. Apparently some users get the ["This extension is not listed in the Chrome Web Store…"](https://github.com/kkkrist/chromium-notifier/issues/14#issuecomment-551690441) error, some "crx required proof missing" – and in my case I can install the crx via drag'n'drop into `chrome://extensions/` with developer mode disabled just fine (Mac, Chromium v79). 

I've updated the README to include this message as well.
