### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by PRFerro** [kkkrist/chromium-notifier#29]
Hi, the extension showed an error icon. This is the content:
![Untitled](https://user-images.githubusercontent.com/59301231/71538684-e61a0500-290d-11ea-9485-3006b399ba81.png)
Is this normal?

**Comment by kkkrist** [comment]
Thanks for reporting! This is definitely not normal behavior. Could you please open the background page devtools of this extension and see if there are any errors shown in the console?

**Comment by PRFerro** [comment]
I'm checking now and it's working fine again:
![Untitled](https://user-images.githubusercontent.com/59301231/71541518-08754800-2939-11ea-86fa-534f82d7e273.png)

Just in case, if I see the error again, where do you want me to look? here right?
More tools >> Extensions >> Inspect views >> background.html
![Untitled2](https://user-images.githubusercontent.com/59301231/71541521-0f9c5600-2939-11ea-9387-750e74c3ab25.png)

**Comment by kkkrist** [comment]
Yes, that's the right place. If you enable "verbose" log messages (click on the "default levels" drop-down) you can also see some general debug info from normal operation.

I guess you caught a little hiccup of the Woolyss API and I can close this issue now. Please re-open if the problem re-appears.

Thanks again for reporting!

**Comment by PRFerro** [comment]
Great, I'll keep you posted if it happens again.
Thanks to you for this very useful extension!
