### ISSUE TITLE
Hibbiki Stable tag missing?

### ISSUE THREAD

**Issue by KevWal** [kkkrist/chromium-notifier#30]
Hi, 

In Tags, you don't list the Hibbiki tag?  I use the Hibbiki version to get the Sync and Google integration included.

Thanks
Kevin

**Comment by kkkrist** [comment]
Hey Kevin,

The Hibbiki tag should be listed if you choose win64 as platform, but it's indeed missing for the win32 platform.

@woolyss Could you please sync all current tags with the API? Thanks!

**Comment by ghost** [comment]
@kkkrist I updated the whole API ;)
Sorry for this inconvenience.

**Comment by kkkrist** [comment]
Thanks a lot!
