### ISSUE TITLE
Version issue with "Bookmark menu"

### ISSUE THREAD

**Issue by Johan46** [kkkrist/chromium-notifier#31]
Hi !

There is no update for "Bookmark Menu", but there is still a notification :

![Capture](https://user-images.githubusercontent.com/5729110/81757990-cea87680-94c0-11ea-8871-98de30466ed4.JPG)

**Comment by kkkrist** [comment]
Thanks for reporting! I'm currently very busy, will look into where the leading zeros get eaten once I got more time.

**Comment by kkkrist** [comment]
So the thing is, while said extension does indeed specify its version *with* leading zeros in its `manifest.json`:

```json
{
"update_url": "https://clients2.google.com/service/update2/crx",

  "name": "Bookmarks Menu",
  "version": "2020.02.02.1",
  "manifest_version": 2,
  "minimum_chrome_version": "64",
  "description": "__MSG_extDescription__",
  "default_locale": "en",
  "browser_action": {
    "default_icon": "icons/icon-24.png",
    "default_popup": "app/popup/popup.html"
  },
  "icons": {
    "16": "icons/icon-16.png",
    "32": "icons/icon-32.png",
    "48": "icons/icon-48.png",
    "128": "icons/icon-128.png"
  },
  "background": {
    "page": "app/background/background.html"
  },
  "options_page": "app/options/options.html",
  "permissions": ["bookmarks", "chrome://favicon/", "fontSettings", "activeTab", "https://*.google.com/"]
}
```

… they are removed by `chrome.management`:
<img width="917" alt="Bildschirmfoto 2020-05-13 um 15 04 03" src="https://user-images.githubusercontent.com/3873068/81816600-d81af880-952b-11ea-9af4-b541e017a2a0.png">

Unfortunately there's no way to retrieve a list of currently installed extensions complete with meta data other than `chrome.management` (afaik at least). I could add a specific workaround for this extension and its custom version number scheme, but that's probably not something very sustainable.

So to really fix this (also for other extension management tools out there), "Bookmark Menu" needs to use a version number scheme that `chrome.management` doesn't feel compelled meddling with (e.g. removing any leading zeros)… or only cut releases on 2-digit days and months ;-)

(Closing… feel free to re-open if you don't agree)
