### ISSUE TITLE
Installation on Version 87.0.4280.88 macOs fails

### ISSUE THREAD

**Issue by felixrupp** [kkkrist/chromium-notifier#32]
Dear @kkkrist,

I tried to install your notifier in a fresh installation of Chromium for macOs, Version 87.0.4280.88 and got the following message:

Package is invalid: "CRX_REQUIRED_PROOF_MISSING".

I am using macOs 10.15.7 and downloaded your latest release version from Github.

Regards,
Felix

**Comment by kkkrist** [comment]
Hey Felix,

have you tried the [installing via "load unpacked extension"](https://github.com/kkkrist/chromium-notifier#installing-via-load-unpacked-extension) method as detailed in the README? As far as I remember more recent/unpatched Chromium versions are blocking unsigned crx packages, such as this extension's.

See also #28 and #14

**Comment by felixrupp** [comment]
Hi @kkkrist,

it finally worked with unzipping the .crx, unfortunately the .crx format has additional data besides the zip-format. It was only possible to unzip with the apple unzip command line tool. The GUI tool was not able to unzip it. Perhaps you can add this information in your readme.

Thanks for your time and best regards,
Felix

**Comment by kkkrist** [comment]
Glad you finally got it working! Btw, you can always grab a zip archive or tarball from the releases page (or just clone the repo), there's no need to unpack the crx.
