### ISSUE TITLE
[Question] chromium.woolyss.com linux

### ISSUE THREAD

**Issue by K-mikaZ** [kkkrist/chromium-notifier#33]
Would there be a chance one day to see the possibility of updating the [marmaduke archive for linux](https://chromium.woolyss.com/#linux)?

**Comment by kkkrist** [comment]
@woolyss Would it be possible to add this to the API? Cheers!

**Comment by ghost** [comment]
Yes. I will add it tomorrow.

**Comment by kkkrist** [comment]
Thanks, Jerry!

**Comment by K-mikaZ** [comment]
> Thanks, Jerry!

Thanks, work fine.
