### ISSUE TITLE
Choose Platform and Tag are greyed out.

### ISSUE THREAD

**Issue by ghost** [kkkrist/chromium-notifier#35]
![image](https://user-images.githubusercontent.com/74547780/115146480-47c52c00-a089-11eb-8320-4a5cb2db81ee.png)
Happened after updating to latest.

**Comment by kkkrist** [comment]
Thanks for reporting. Looks like the initial API call failed. There's a delay of around 3h before it's going to try again. You can speed this up by reinstalling.

**Comment by CBearr** [comment]
Reinstall don't solve this issue.

![Screenshot 2021-04-19 090155](https://user-images.githubusercontent.com/82800336/115194676-0f0b6e00-a0ee-11eb-90bd-2a395e97cefa.jpg)
![Screenshot 2021-04-19 090218](https://user-images.githubusercontent.com/82800336/115194701-1468b880-a0ee-11eb-8634-ada3b528e654.jpg)
![Screenshot 2021-04-19 090237](https://user-images.githubusercontent.com/82800336/115194710-1894d600-a0ee-11eb-958b-2865aae12a6b.jpg)

**Comment by kkkrist** [comment]
Thanks for posting the screenshots with the error message. Now I know what's going on. 

@woolyss Jerry, I see you've removed the `access-control-allow-origin` http header from your api's response. Is there a reason for this? It was previously set to `*`. Should I explicitly request permission to access the api host via manifest to fix this or can you add it back?

**Comment by ghost** [comment]
Hello to all ;)

Sorry I removed the `access-control-allow-origin` http header to more protect my server.

I re-added it only for my Chromium sub-domain ;)
https://securityheaders.com/?q=https%3A%2F%2Fchromium.woolyss.com%2F

**Comment by kkkrist** [comment]
Thank you for the quick fix! If it causes you any problems I can always extend permissions.

@CBearr @CHAINSAWMANN Can you confirm it's working again?

**Comment by ghost** [comment]
Works fine now. Thanks!

**Comment by ghost** [comment]
Super ;)

Thank you all for your report.

Have a good day!

You can close this issue ;)

**Comment by kkkrist** [comment]
Thanks again Jerry, keep up the good work :-)

**Comment by CBearr** [comment]
Yes, works. Thank you
