### ISSUE TITLE
UA Reduction considerations

### ISSUE THREAD

**Issue by pointydev** [kkkrist/chromium-notifier#36]
Hey there,

At the moment, the notifier uses the user agent to determine whether or not the current browser is out of date. This may not be as reliable in the future as [UA reduction](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html) is slated to start rolling out soon. This behaviour can be tested via the `#reduce-user-agent` or `#freeze-user-agent` (pre-M93).

![](https://the.uwu.foundation/7NyRKyA.png)

A more reliable way to handle this situation in the future may be to use `navigator.userAgentData.getHighEntropyValues(["uaFullVersion"])`, with the current method as a fallback.

* Additional resources:
  * [Chromium Blog: Update on User-Agent String Reduction in Chrome](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html)
  * [Chromium updates > User-Agent Reduction](https://www.chromium.org/updates/ua-reduction)
  * [Migrate to User-Agent Client Hints](https://web.dev/migrate-to-ua-ch/)
  * [UA-CH JS test](https://user-agent-client-hints.glitch.me/javascript.html)

Thanks,
Elliott

**Comment by kkkrist** [comment]
Elliott,

I've incorporated the changes you've suggested into branch [v1.8.5-rc.0](https://github.com/kkkrist/chromium-notifier/tree/v1.8.5-rc.0). Could you try this branch out and provide some feedback?

Thank you for bringing this up, it's much appreciated!

–Christian

**Comment by pointydev** [comment]
Tested on Marmaduke's `92.0.4515.107` [ungoogled](https://github.com/macchrome/winchrome/releases/tag/v92.0.4515.107-r885287-Win64) build, seems to be working both with and without the flag:
![92.0.4515.107 ungoogled screenshot](https://the.uwu.foundation/7bYfxkK.png)

Also tested on an official `87.0.4280.0` [r812845](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/812845/) build, where `navigator.userAgentData` isn't present, also working:
<details><summary>Screenshot</summary>

![87.0.4280.0 screenshot](https://the.uwu.foundation/7zR4tLH.png)</details>

Seems ready for release when the version number gets bumped, thanks again!
~Elliott
