### ISSUE TITLE
Version number no longer visible

### ISSUE THREAD

**Issue by CBearr** [kkkrist/chromium-notifier#39]
Hallo,

seit ein paar Wochen wird die Versionsnummer vom Win64 Dev official nicht mehr im Addon angezeigt. Auf der offiziellen Website ebenso nicht mehr.

![Screenshot 2021-11-04 092056](https://user-images.githubusercontent.com/82800336/140280570-457285bf-0c95-40c7-9952-9bb242021030.jpg)
![Screenshot 2021-11-04 092135](https://user-images.githubusercontent.com/82800336/140280659-b5f0e1fb-2942-4bd2-ae9e-e935c1f77332.jpg)

Mit freundlichen Grüßen

**Comment by kkkrist** [comment]
@woolyss: looking at the API response, `version` is currently missing for the `dev-official` tags in `win64` and `win32` and incorrectly showing `"0.0.0.0"` in `mac` and `android`. Could you take a look at what's going on? Thanks!

**Comment by ghost** [comment]
Hi everybody,
I will check that this weekend. Thank you very much for your report.

**Comment by kkkrist** [comment]
Just checked again, seems to be fixed now. Thanks @woolyss!
