### ISSUE TITLE
Extension Updates show the same Version-Number as new

### ISSUE THREAD

**Issue by devdracon** [kkkrist/chromium-notifier#40]
Since the last version of the "Update Notifications Plugin" (1.8.6), the extension manager shows the same version number as "new" for many plug-ins. The information displayed is not correct; the plug-ins do not have this version number in the current version.

![Bildschirmfoto 2021-11-10 um 07 29 40](https://user-images.githubusercontent.com/73227523/141062282-0345be5c-f452-4500-9a9b-7ceef27d99b0.png)

**Comment by kkkrist** [comment]
Thanks for reporting this bug! By supporting extensions installed via "Load unpacked extension" I've messed up support for listed extensions, sorry! It should be fixed in [v1.8.7](https://github.com/kkkrist/chromium-notifier/releases/tag/v1.8.7)

**Comment by devdracon** [comment]
Christian, thank you for the fast and continuing support!
