### ISSUE TITLE
Errors in the extension after updating to Chromium 96

### ISSUE THREAD

**Issue by ivan123-tty** [kkkrist/chromium-notifier#41]
![image](https://user-images.githubusercontent.com/70339505/142043121-d372aacd-db9a-41ea-ab1a-621667f3cdda.png)

**Comment by kkkrist** [comment]
Thank you for bringing this up! 

Not sure what's going on here, but this only seems to happen after upgrading from Chromium v95 to v96. Installing the extension afresh on v96 works fine on my end. So please try re-installing chromium-notifier and report back!

**Comment by ivan123-tty** [comment]
> Thank you for bringing this up!
> 
> Not sure what's going on here, but this only seems to happen after upgrading from Chromium v95 to v96. Installing the extension afresh on v96 works fine on my end. So please try re-installing chromium-notifier and report back!

for some reason, the extension works just fine now. i didn't even need reinstalling it.

**i think, that issue can be closed now.**

**Comment by kkkrist** [comment]
Thank you for the feedback! I think extension update data written to storage in v95 cannot be read on v96 for some reason. So it needs to be re-fetched and overwritten once you've upgraded to v96. There are 3 ways to do it:

- Re-install the extension (wipes storage)
- Turn "Track extension updates" off and on again (triggers re-fetch)
- Just wait until the data gets re-fetched automatically (every ~3h)
